# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portree < Formula
  desc "Git Worktree Server Manager"
  homepage "https://github.com/fairy-pitta/portree"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fairy-pitta/portree/releases/download/v0.5.0/portree_0.5.0_darwin_amd64.tar.gz"
      sha256 "f796dcfb23b8c5d60b900303a1adb8819db17b54686fcc36eb36a05e6a48a3df"

      define_method(:install) do
        bin.install "portree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fairy-pitta/portree/releases/download/v0.5.0/portree_0.5.0_darwin_arm64.tar.gz"
      sha256 "a3b37fb9e538395717e5f65cca0de35965cae10b2080b49cdcc5efeffe4df456"

      define_method(:install) do
        bin.install "portree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fairy-pitta/portree/releases/download/v0.5.0/portree_0.5.0_linux_amd64.tar.gz"
      sha256 "7cc4d949bef68ed51978145b494139bddfa1396203dd2197a76c9fc1cdb7c5d3"
      define_method(:install) do
        bin.install "portree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fairy-pitta/portree/releases/download/v0.5.0/portree_0.5.0_linux_arm64.tar.gz"
      sha256 "db1d393fb678bb38f329845396fcfdc4c8e30365787d8541e93bde8078ea9153"
      define_method(:install) do
        bin.install "portree"
      end
    end
  end

  test do
    system "#{bin}/portree", "version"
  end
end
