# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portree < Formula
  desc "Git Worktree Server Manager"
  homepage "https://github.com/fairy-pitta/portree"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fairy-pitta/portree/releases/download/v0.2.0/portree_0.2.0_darwin_amd64.tar.gz"
      sha256 "7df537941efa9316eee9c3614b38ffcabd424921f484b4c15bcaebb807d2f8af"

      define_method(:install) do
        bin.install "portree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fairy-pitta/portree/releases/download/v0.2.0/portree_0.2.0_darwin_arm64.tar.gz"
      sha256 "f75b1e27535770c5969adfd51c53f2ceaa341add0851dd0ef94171acaa54e9c7"

      define_method(:install) do
        bin.install "portree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fairy-pitta/portree/releases/download/v0.2.0/portree_0.2.0_linux_amd64.tar.gz"
      sha256 "ec3ac61e0a5160489a9e9238d7ea8ab25be97404c109b30d928fbc401545ddc6"
      define_method(:install) do
        bin.install "portree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fairy-pitta/portree/releases/download/v0.2.0/portree_0.2.0_linux_arm64.tar.gz"
      sha256 "3c3ea59317e283ddbd4de921df0c14cbb784aa5fac452c264ed1f7addbdb258f"
      define_method(:install) do
        bin.install "portree"
      end
    end
  end

  test do
    system "#{bin}/portree", "version"
  end
end
